site_name: "blog"
site_url: "https://piper-of-dawn.github.io/blog/"
site_description: "Documentation that also shines"
site_author: "Kumar Shantanu <kumarshan25@gmail.com>"
dev_addr: "127.0.0.1:8080"
repo_url: "https://github.com/piper-of-dawn/blog"
extra_css:
  - css/custom.css
theme:
  name: shadcn
  icon: null
  topbar_sections: false
  pygments_style:
    light: shadcn-light
    dark: github-dark
  katex_options:
    trust: true
    macros:
      "\\dx": "\\mathrm{d}x"
      "\\NN": "\\mathbb{N}"
  # show_datetime: true
  # accent: "oklch(64.5% 0.246 16.439)"

plugins:
  - search
  - excalidraw
  - mkdocstrings
  - autonumber:
      prefixes:
        th: Theorem

markdown_extensions:
  admonition:
  shadcn.extensions.obsidian_callouts:
  codehilite:
  fenced_code:
  footnotes:
  extra:
  pymdownx.details:
  pymdownx.blocks.details:
  pymdownx.tabbed:
  pymdownx.blocks.tab:
    combine_header_slug: true
    separator: ___
  pymdownx.progressbar:
  pymdownx.snippets:
  pymdownx.arithmatex:
    generic: true
  shadcn.extensions.echarts.alpha:
  shadcn.extensions.codexec:
  shadcn.extensions.iconify:
  pymdownx.blocks.caption:
  shadcn.extensions.hover_card:
